from .box_attribute_changed import OnBoxAttributeChangedEventListener
from .box_created import OnBoxCreatedEventListener
from .box_deleted import OnBoxDeletedEventListener
from .box_moved import OnBoxMovedEventListener
from .classify_traffic_light import OnClassifyTrafficLightEventListener
from .end_of_stream import OnEndOfStreamEventListener
from .extract_box import OnExtractBoxEventListener
from .frame_added import OnFrameAddedEventListener
